### ISSUE TITLE
Depenency Issue! yum-repoforge uses what looks like a dead resource "mirror list".

### ISSUE THREAD

**Issue by pbattilega** [Alfresco/chef-alfresco#85] opened 2016-07-21 04:45 UTC
Test builds are breaking because yum is unable to build a mirror list.

Example error:
    amazon-ebs: +[rpmforge]
    amazon-ebs: +name=RHEL $releasever - RPMforge.net - dag
    amazon-ebs: +enabled=1
    amazon-ebs: +gpgcheck=1
    amazon-ebs: +gpgkey=http://apt.sw.be/RPM-GPG-KEY.dag.txt
    amazon-ebs: +mirrorlist=http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
--- cut--
amazon-ebs: execute[yum-makecache-rpmforge] (/tmp/packer-chef-client/local-mode-cache/cache/cookbooks/yum/providers/repository.rb line 69) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'

The url / resource http://mirrorlist.repoforge.org/el7/mirrors-rpmforge returns 0 bytes "no list".

Alfresco files:
metadata.rb:
depends 'yum-repoforge', ">= 0.5.1"
recipes/package-repositories.rb:
include_recipe 'yum-repoforge::default'

The resource  used by the dependency yum-repoforge is considered dead according to the CentOS wiki.

See:
https://wiki.centos.org/AdditionalResources/Repositories
“RPMForge/RepoForge - This is a dead project. Not maintained. DO NOT USE. ”

See also :
https://github.com/chef-cookbooks/yum-repoforge/issues/13?_pjax=%23js-repo-pjax-container

Looks as if the maintainer has recognized the issue.

**Comment by enzor** [comment] 2016-07-21 08:06
Hi peter,

thanks for your feedback.
After some investigation I found out that the mirrorlist webpage is based on the github repo https://github.com/davidhrbac/mirrorlist , which contains all the mirrorlist we need and is relatively stable (last change was ~3 years ago).
I am currently testing a quick fix for this by overriding the default rmpforge mirrorlist url to unblock you and all chef-alfresco user...however this is by no mean a definitive solution, and I will consult my team on how to handle best this problem with the tools at our disposal.

**Comment by cvakiitho** [comment] 2016-07-21 09:21
Hi guys,

just sent an email to repoforge mirrors mailing list http://lists.repoforge.org/mailman/listinfo/mirrors so they get notified as well.

**Comment by enzor** [comment] 2016-07-21 09:48
hi @cvakiitho , thank you.
I am also testing if chef-alfresco actually needs rpmforge. 
If this is not the case, i'd be happy to remove it's cookbook, as it should be a dead repo now.

**Comment by enzor** [comment] 2016-07-21 13:49
resolved with #86 
Turns out chef-alfresco didn't need rpmforge. Removing it yielded the same result

**Comment by enzor** [comment] 2016-07-21 17:41
after talking with @pbattilega i can confirm that the converge works now. 
Closing the issue

**Closed by enzor** 2016-07-21 17:41 UTC
